# Generated by Django 4.1.2 on 2023-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='time',
        ),
        migrations.AddField(
            model_name='data',
            name='hadith',
            field=models.TextField(blank=True, null=True),
        ),
    ]
