# Generated by Django 4.1.2 on 2023-06-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0002_remove_data_date_remove_data_time_data_hadith'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
