# Generated by Django 4.1.2 on 2023-06-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0004_data_asaradhan_data_asariqama_data_audio_data_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='time',
        ),
        migrations.AddField(
            model_name='data',
            name='time_difference',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
