# Generated by Django 4.1.2 on 2023-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsrc', '0005_remove_data_date_remove_data_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
